### ISSUE TITLE
Some issues when installing to chrome

### ISSUE THREAD

**Issue by auto-responder** [navendu-pottekkat/nsfw-filter#7] opened 2020-07-18 00:23 UTC
See below.

## Expected Behavior

It should not have the below errors in the Chrome extensions manager.

## Current Behavior

Chrome lists these issues after loading the unpacked `dist` directory

Overriding the gradient for 'Max'
Overriding the gradient for 'OneHot'
Overriding the gradient for 'PadV2'
Overriding the gradient for 'SpaceToBatchND'
Overriding the gradient for 'SplitV'

## Possible Solution

n/a

## Steps to Reproduce (for bugs)

1. Install using repo's instructions on Chrome for Mac v84.0.4147.89

## Context

As a result, no NSFW images are blocked.

## Your Environment

* Version used: v0.2.2-beta
* Browser Name and version: 64-bit Chrome for Mac v84.0.4147.89
* Operating System and version: macOS Cataline v10.15.4
* Link to your project: n/a

**Comment by willsmanley** [comment] 2020-07-18 00:26
And I receive these errors in Firefox:

```
Reading manifest: Warning processing permissions: Error processing permissions.1: Value "declarativeContent" must either: must either [must either [must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], or be one of ["webNavigation"]], be one of ["alarms", "mozillaAddons", "storage", "unlimitedStorage"], be one of ["captivePortal"], be one of ["identity"], be one of ["menus", "contextMenus"], be one of ["normandyAddonStudy"], be one of ["geckoProfiler"], be one of ["urlbar"], be one of ["contextualIdentities"], be one of ["dns"], be one of ["activityLog"], be one of ["networkStatus"], be one of ["telemetry"], or be one of ["theme"]], must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], or be one of ["webNavigation"]], be one of ["nativeMessaging"], or match the pattern /^experiments(\.\w+)+$/], or must either [be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/]
```

**Comment by willsmanley** [comment] 2020-07-18 00:37
Sorry to have created an issue about this, as maybe it is not an issue after all. Now I have tested it again and see that it is working, but with a bit of a lag. That threw me off. I assume the errors are expected as part of the beta phase.

**Comment by navendu-pottekkat** [comment] 2020-07-18 05:19
The warnings shown in Chrome is from TensorFlow JS. This would be fixed in the next release of TensorFlow. It does not cause a problem. Errors are expected when running in a developer environment right? This would not be shown when you actually install it from the store. (It is available in Firefox store)

The lag there has been fixed and would be updated in the next release. The model will then be run as soon as the images are loaded!

Also, there seem to be some issues in the manifest for Firefox, as you have shown. If you have a solution, make a PR and I would be happy to add it.

And I have released it even though it is in development so that the software can be tested and contributed to by more people. So do contribute!

**Comment by navendu-pottekkat** [comment] 2020-07-18 09:11
Fixed the loading issue and added it to the latest release

**Comment by willsmanley** [comment] 2020-07-19 22:38
@navendu-pottekkat would it make sense to add a feature (or standard behavior) wherein the images on a webpage are all blurred until they have confirmed to be safe? At the moment, even a small lag defeats the purpose because the user sees a flash of the image. It would be pretty hard to get it to reliably less than the ~50 ms time that human eyes take to perceive something. Thanks for the great extension!

**Comment by navendu-pottekkat** [comment] 2020-07-20 04:34
That is a good idea. I will try that. You can also try to add that feature. Just make a PR in the feature updates branch. I have also added options for the user to select how to filter out the images from a pop-up. It is not finished yet but most of the code is written. You can add a function in that that would blur the images before they are passed to the model and unblur only of they are safe.

**Comment by willsmanley** [comment] 2020-07-22 06:51
@navendu-pottekkat thanks. another thing that would be nice would be to disable the console logging for the production build of the extension. When I am working on other projects, these logs would be nice to eliminate, especially on pages with lots of images.

**Comment by navendu-pottekkat** [comment] 2020-07-22 07:07
@willsmanley This is already implemented. You can check the content.js file and set debug to 0. This would prevent the extension from logging anything in the console. Since this is under development by default it is set to 1. You can change that to make it work!

**Comment by willsmanley** [comment] 2020-07-24 00:07
nice that works for me!

I found from my Nodejs implementation of the NSFWJS model that it was most effective to block images by adding together the probabilities for Sexy + Porn + Hentai instead of relying on any single probability. Some images are inappropriate and will be like 40% porn and 40% sexy. Combining those categories makes it a lot clearer.

I still haven't looked into your code and what your logic is, but hopefully that helps a bit.

**Comment by navendu-pottekkat** [comment] 2020-07-26 13:40
@all-contributors please add @anonacc for bug

**Closed** 2020-07-27 16:44 UTC
Labels: dependency bug, good first issue, known issue
